n = int(input('Digite um número: '))
print(f'{n} x 2 é igual a {n*2}')
print(f'{n} x 3 é igual a {n*3}')
print(f'{n} x 4 é igual a {n*4}')
print(f'{n} x 5 é igual a {n*5}')
print(f'{n} x 6 é igual a {n*6}')
print(f'{n} x 7 é igual a {n*7}')
print(f'{n} x 8 é igual a {n*8}')
print(f'{n} x 9 é igual a {n*9}')
print(f'{n} x 10 é igual a {n*10}')
