times = ('Flamengo', 'Palmeiras', 'santos', 'Grêmio', 'Cruzeiro', 'Corinthians', 'Vasco', 'Chapecoense', 'Atlético', 'Botafogo', 'Atlético-PR', 'Bahia', 'São Paulo', 'Fluminense', 'Sport Recife', 'EC Vitória', 'Coritiba', 'Avaí', 'Ponte Preta', 'Atlético-go')
print('=-='*12)
print(f'os 5 primeiros colocados são: {times[0:6]}')
print('=-='*12)
print(f'Os últimos colocados são: {times[-4:]}')
print('=-='*12)
print('Os times em ordem alfabetica são: ', sorted(times))
print('=-='*12)
print(f'A chapecoense está em {times.index("Chapecoense")+1}° lugar')
print('=-='*12)
